services:
  backend:
    container_name: spring_back
    image: spring_angular_example
    build: 
      context: backend
      target: builder
    networks:
      - net
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
  frontend:
    container_name: angular_front
    image: angular_front
    build: 
      context: frontend
      target: builder
    networks:
      - net
    expose:
      - 4200
    ports:
      - 4200:4200
    depends_on:
      - backend

networks:
  net: