spring:
  application.name: backend
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: sa
    password: pass
    driverClassName: org.h2.Driver
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub